'use client';

import { useState, useEffect, useRef } from 'react';
import DashboardLayout from '../../components/DashboardLayout';
import { useAuth } from '../../context/AuthContext';
import { apiFetch } from '../../lib/api';
import { Html5QrcodeScanner, Html5Qrcode } from 'html5-qrcode';
import QRCode from 'react-qr-code';

const navItems = [
  { id: 'home', label: 'Dashboard', icon: '🏠' },
  { id: 'attendance', label: 'Attendance', icon: '📋' },
  { id: 'gatepass', label: 'Gate Pass', icon: '🎫' },
];

function StudentHome({ user }) {
  const now = new Date();
  const istTime = new Intl.DateTimeFormat('en-IN', {
    timeZone: 'Asia/Kolkata',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  }).format(now);

  const istDate = new Intl.DateTimeFormat('en-IN', {
    timeZone: 'Asia/Kolkata',
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(now);

  return (
    <>
      <div className="page-header">
        <h1 className="page-title">Welcome back, {user.name.split(' ')[0]}! 👋</h1>
        <p className="page-subtitle">{istDate} • {istTime} IST</p>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-header">
            <span className="stat-label">Today&apos;s Attendance</span>
            <div className="stat-icon" style={{ background: 'var(--success-bg)', color: 'var(--success)' }}>📋</div>
          </div>
          <div className="stat-value" style={{ color: 'var(--text-muted)' }}>—</div>
          <div className="stat-label">See Attendance Tab</div>
        </div>

        <div className="stat-card">
          <div className="stat-header">
            <span className="stat-label">Gate Passes</span>
            <div className="stat-icon" style={{ background: 'var(--info-bg)', color: 'var(--info)' }}>🎫</div>
          </div>
          <div className="stat-value" style={{ color: 'var(--text-muted)' }}>0</div>
          <div className="stat-label">Active passes</div>
        </div>

        <div className="stat-card">
          <div className="stat-header">
            <span className="stat-label">Room</span>
            <div className="stat-icon" style={{ background: 'var(--warning-bg)', color: 'var(--warning)' }}>🚪</div>
          </div>
          <div className="stat-value">{user.room_no || '—'}</div>
          <div className="stat-label">{user.hostel_id}</div>
        </div>
      </div>
    </>
  );
}

function AttendanceScanner({ onScanSuccess }) {
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);
  const [scannerReady, setScannerReady] = useState(false);
  
  useEffect(() => {
    // Only init inside a timeout to avoid strict mode double render clashes
    const timer = setTimeout(() => {
      setScannerReady(true);
      const scanner = new Html5QrcodeScanner('qr-reader', { 
        fps: 10,
        qrbox: { width: 250, height: 250 },
        aspectRatio: 1.0,
      }, false);
      
      scanner.render((decodedText) => {
        // Pause to prevent re-scanning
        scanner.pause(true);
        handleScan(decodedText, scanner);
      }, (err) => {
        // Silently ignore normal scan parsing errs until successful
      });
      
      return () => {
        scanner.clear().catch(e => console.error("Failed to clear scanner", e));
      };
    }, 100);
    
    return () => clearTimeout(timer);
  }, []);

  const handleScan = async (qrToken, scanner) => {
    try {
      setLoading(true);
      setError('');
      setSuccess('');
      
      const res = await apiFetch('/attendance/scan', {
        method: 'POST',
        body: JSON.stringify({ qrToken })
      });
      
      setSuccess(`✅ Attendance marked successfully! Status: ${res.result.status.toUpperCase()}`);
    } catch (err) {
      setError(`❌ ${err.message || 'Failed to mark attendance. Invalid QR?'}`);
      // Resume scanning on error after 3 seconds
      setTimeout(() => scanner.resume(), 3000);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <div className="page-header">
        <h1 className="page-title">Attendance Scanner</h1>
        <p className="page-subtitle">Scan the daily QR code generated by the Warden</p>
      </div>
      
      <div style={{ maxWidth: '500px', margin: '0 auto' }}>
        {error && (
          <div className="alert alert-error" style={{ marginBottom: '1rem' }}>
            {error}
          </div>
        )}
        
        {success && (
          <div className="alert alert-success" style={{ marginBottom: '1rem' }}>
            {success}
          </div>
        )}
        
        <div className="card" style={{ display: success ? 'none' : 'block' }}>
          <div id="qr-reader" style={{ width: '100%', minHeight: '300px' }}></div>
          {loading && (
            <div style={{ textAlign: 'center', marginTop: '1rem' }}>
              <span className="spinner" style={{ display: 'inline-block' }}></span>
              <span style={{ marginLeft: '10px' }}>Processing scan...</span>
            </div>
          )}
        </div>
        
        {/* Helper debug box for manual entry during testing */}
        <div className="card" style={{ marginTop: '2rem' }}>
           <h4 style={{ marginBottom: '0.5rem', fontSize: '0.8rem', color: 'var(--text-muted)' }}>MOCK/TEST MANUAL ENTRY</h4>
           <div style={{ display: 'flex', gap: '0.5rem' }}>
             <input type="text" id="manual-qr-input" className="form-input" placeholder="Paste UUID here..." />
             <button className="btn btn-secondary" onClick={() => {
                const val = document.getElementById('manual-qr-input').value;
                if(val) handleScan(val, { resume: () => {} });
             }}>Simulate</button>
           </div>
        </div>
      </div>
    </>
  );
}

function GatePassPanel() {
  const [passes, setPasses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  
  // Form state
  const [reason, setReason] = useState('');
  const [expectedOut, setExpectedOut] = useState('');
  const [expectedReturn, setExpectedReturn] = useState('');
  const [requestLoading, setRequestLoading] = useState(false);

  useEffect(() => {
    fetchPasses();
  }, []);

  const fetchPasses = async () => {
    try {
      setLoading(true);
      const data = await apiFetch('/gatepass/student');
      setPasses(data);
    } catch (err) {
      console.error(err);
      setError('Failed to load your active and historical passes.');
    } finally {
      setLoading(false);
    }
  };

  const handleRequest = async (e) => {
    e.preventDefault();
    try {
      setRequestLoading(true);
      setError('');
      
      await apiFetch('/gatepass/request', {
        method: 'POST',
        body: JSON.stringify({ reason, expectedOut, expectedReturn })
      });
      
      setReason('');
      setExpectedOut('');
      setExpectedReturn('');
      
      await fetchPasses(); // Reload passes
    } catch (err) {
      setError(err.message || 'Failed to submit request.');
    } finally {
      setRequestLoading(false);
    }
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'approved': return <span className="badge badge-success">Approved</span>;
      case 'active': return <span className="badge badge-success">Active (Out)</span>;
      case 'pending': return <span className="badge badge-warning">Pending</span>;
      case 'overdue': return <span className="badge badge-danger blink">Overdue!</span>;
      case 'unresolved': return <span className="badge badge-danger">Unresolved</span>;
      case 'rejected': return <span className="badge badge-danger">Rejected</span>;
      default: return <span className="badge badge-info">{status}</span>;
    }
  };

  return (
    <>
      <div className="page-header">
        <h1 className="page-title">Gate Pass</h1>
        <p className="page-subtitle">Request and manage your gate passes</p>
      </div>

      {error && <div className="alert alert-error" style={{marginBottom: '1rem'}}>{error}</div>}

      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 2fr)', gap: '1.5rem', alignItems: 'start' }}>
        
        {/* New Request Form */}
        <div className="card">
          <h3 style={{ marginBottom: '1rem' }}>New Request</h3>
          <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>
            Note: Requests cannot be submitted between 9:00 PM and 6:00 AM.
          </p>
          <form onSubmit={handleRequest}>
            <div className="form-group">
              <label className="form-label">Reason</label>
              <textarea
                className="form-input"
                rows="3"
                value={reason}
                onChange={(e) => setReason(e.target.value)}
                required
              />
            </div>
            <div className="form-group">
              <label className="form-label">Expected Leave Time</label>
              <input
                type="datetime-local"
                className="form-input"
                value={expectedOut}
                onChange={(e) => setExpectedOut(e.target.value)}
                required
              />
            </div>
            <div className="form-group">
              <label className="form-label">Expected Return Time</label>
              <input
                type="datetime-local"
                className="form-input"
                value={expectedReturn}
                onChange={(e) => setExpectedReturn(e.target.value)}
                required
              />
            </div>
            <button type="submit" className="btn btn-primary btn-full" disabled={requestLoading}>
              {requestLoading ? 'Submitting...' : 'Submit Request'}
            </button>
          </form>
        </div>

        {/* Passes List */}
        <div className="card">
          <h3 style={{ marginBottom: '1rem' }}>Your Passes</h3>
          
          {loading ? (
             <div style={{ textAlign: 'center', padding: '2rem' }}><span className="spinner"></span></div>
          ) : passes.length === 0 ? (
             <div className="empty-state">
                <div className="empty-state-icon">🎫</div>
                <div className="empty-state-text">No passes yet</div>
             </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {passes.map(pass => (
                <div key={pass.id} style={{ border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', padding: '1rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.5rem' }}>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: '1rem' }}>{pass.reason}</div>
                      <div style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)' }}>
                         Out: {new Date(pass.expected_out).toLocaleString()}<br/>
                         Return: {new Date(pass.expected_return).toLocaleString()}
                      </div>
                    </div>
                    <div>{getStatusBadge(pass.status)}</div>
                  </div>
                  
                  {pass.approval_note && (
                    <div style={{ fontSize: '0.8125rem', padding: '0.5rem', background: 'var(--bg-input)', borderRadius: '4px', marginTop: '0.5rem' }}>
                      <span style={{ fontWeight: 600 }}>Warden Note: </span> {pass.approval_note}
                    </div>
                  )}

                  {/* If pass is approved or active, show the QR code token securely */}
                  {pass.qr_token && (pass.status === 'approved' || pass.status === 'active' || pass.status === 'overdue') && (
                     <div style={{ marginTop: '1rem', display: 'flex', gap: '1rem', alignItems: 'center', background: 'white', padding: '1rem', borderRadius: '8px', color: 'black' }}>
                       <QRCode value={pass.qr_token} size={100} />
                       <div style={{ fontSize: '0.75rem' }}>
                         <strong>Security Pass QR</strong><br/>
                         Present this at the security gate for scanning.
                       </div>
                     </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

      </div>
    </>
  );
}

export default function StudentDashboard() {
  const [activeTab, setActiveTab] = useState('home');
  const { user } = useAuth();

  return (
    <DashboardLayout role="student" navItems={navItems} activeTab={activeTab} onTabChange={setActiveTab}>
      {activeTab === 'home' && user && <StudentHome user={user} />}
      {activeTab === 'attendance' && <AttendanceScanner />}
      {activeTab === 'gatepass' && <GatePassPanel />}
    </DashboardLayout>
  );
}
